# sample grid map fusion parameters for sample sensor kit
/**:
    ros__parameters:
      fusion_map_length_x: 100.0     # [m]
      fusion_map_length_y: 100.0     # [m]
      fusion_map_resolution: 0.5 # [m]

      # Setting1: tune ogm creation parameters
      obstacle_pointcloud_topic: "/perception/obstacle_segmentation/single_frame/pointcloud_raw"
      each_raw_pointcloud_topics:
        - "/sensing/lidar/top/outlier_filtered/pointcloud_synchronized"
        - "/sensing/lidar/left/outlier_filtered/pointcloud_synchronized"
        - "/sensing/lidar/right/outlier_filtered/pointcloud_synchronized"
      each_ogm_output_topics:
        - "/perception/occupancy_grid_map/top_lidar/map"
        - "/perception/occupancy_grid_map/left_lidar/map"
        - "/perception/occupancy_grid_map/right_lidar/map"
      each_ogm_sensor_frames:
        - "velodyne_top"
        - "velodyne_left"
        - "velodyne_right"
      # reliability of each sensor (0.0 ~ 1.0) only work with "log-odds" and "dempster-shafer"
      each_ogm_reliabilities:
        - 1.0
        - 0.6
        - 0.6

      # Setting2: tune ogm fusion parameters
      ## choose fusion method from ["overwrite", "log-odds", "dempster-shafer"]
      fusion_method: "overwrite"

      # grid map coordinate
      map_frame: "map"
      base_link_frame: "base_link"
      # center of the grid map
      gridmap_origin_frame: "base_link"
